<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            ['300.01.A01', 'APOTEK', 'NON PPN', 'OBAT'],
            ['300.01.A02', 'PT ANTARMITRA SEMBADA INHEALTH', 'PPN', 'OBAT'],
            ['300.01.A03', 'PT ANUGERAH PHARMINDO LESTARI INHEALTH', 'PPN', 'OBAT'],
            ['300.01.A04', 'PT ANUGERAH PHARMINDO LESTARI', 'PPN', 'OBAT'],
            ['300.01.A05', 'PT ANTARMITRA SEMBADA', 'PPN', 'OBAT'],
            ['300.01.A06', 'PT ANUGRAH ARGON MEDICA INHEALTH', 'PPN', 'OBAT'],
            ['300.01.A07', 'PT ANTARMITRA SEMBADA LKPP', 'PPN', 'OBAT'],
            ['300.01.A08', 'PT ANUGRAH ARGON MEDICA', 'PPN', 'OBAT'],
            ['300.01.A09', 'PT EXZER AMSAL MANDIRI', 'PPN', 'ALKES'],
            ['300.01.A10', 'PT ANUGERAH PHARMINDO LESTARI LKPP', 'PPN', 'OBAT'],
            ['300.01.A11', 'PT ANUGRAH ARGON MEDICA LKPP', 'PPN', 'OBAT'],
            ['300.01.A12', 'APOTEKA INDONUSA UTAMA', 'PPN', 'ALKES'],
            ['300.01.A13', 'PT ADYA ARTA ABADI', 'PPN', 'OBAT'],
            ['300.01.A14', 'PT ALLAVAMAED NUVOAN ADIGUNA', 'PPN', 'ALKES'],
            ['300.01.A15', 'PT ERA KILAT WICAKSANA', 'PPN', 'ALKES'],
            ['300.01.A16', 'PT ALEXA MEDIKA', 'PPN', 'ALKES'],
            ['300.01.A17', 'PT ALLVAMED NUVACON ADIGANA', 'PPN', 'ALKES'],
            ['300.01.A18', 'PT EUREKA SUKSES ABADI', 'PPN', 'ALKES'],
            ['300.01.A19', 'PT AKARIM JAYA FARMA', 'PPN', 'ALKES'],
            ['300.01.A20', 'PT ADYA ARTHA ABADI', 'PPN', 'OBAT'],
            ['300.01.A21', 'ASUI', 'NON PPN', 'ATK'],
            ['300.01.A22', 'ACC ADVERTISING', 'NON PPN', 'ALKRILIK'],
            ['300.01.A23', 'PT SAMATOR INDO GAS TBK', 'PPN', 'GAS MEDIS'],
            ['300.01.A24', 'A I', 'NON PPN', 'IKAN'],
            ['300.01.A25', 'PT GARUDA PERKASA INTIMEDIKA', 'PPN', 'OBAT'],
            ['300.01.A26', 'PT GENERAL MEDICAL SUPPLIER', 'PPN', 'ALKES'],
            ['300.01.A27', 'AHUI', 'NON PPN', 'SAYUR-SAYURAN'],
            ['300.01.A28', 'PT ANUGERAH REZEKI BERSAMA INDONESIA', 'PPN', 'OBAT'],
            ['300.01.A29', 'PT ANUGERAH MUTIARA NUSANTARA', 'PPN', 'ALKES'],
            ['300.01.A30', 'PT INDOMEDIKA SOLUSINDO', 'PPN', 'ALKES'],
            ['300.01.A31', 'ANUGERAH PANGLONG', 'NON PPN', 'PERABOT'],
            ['300.01.A32', 'PT ALFA MITRA INTERNUSA', 'PPN', 'PLASTIK WRAPPING'],
            ['300.01.A33', 'ARASHI', 'NON PPN', 'DISPENSER'],
            ['300.01.A34', 'ASIA JAYA', 'NON PPN', 'ELEKTRONIK'],
            ['300.01.A35', 'AUVI SELULAR', 'NON PPN', 'HANDPHONE'],
            ['300.01.A36', 'PT ABADI MAKMUR BERSAMA', 'PPN', 'ALKES'],
            ['300.01.A37', 'PT ANDALAN INOVASI RUANGAN', 'PPN', 'VINYL'],
            ['300.01.A38', 'PT ALFA PRIMA NUSINDO', 'PPN', 'ALKES'],
            ['300.01.A39', 'PT ADYA ARTHA ABADI INHEALTH', 'PPN', 'OBAT'],
            ['300.01.B01', 'PT BRATACO', 'PPN', 'ALKES'],
            ['300.01.B02', 'PT BINA SAN PRIMA', 'PPN', 'OBAT'],
            ['300.01.B03', 'PT BINA SAN PRIMA INHEALTH', 'PPN', 'OBAT'],
            ['300.01.B04', 'CV BUANA MAS', 'NON PPN', 'ALKES'],
            ['300.01.B05', 'PT BINA SAN PRIMA LKPP', 'PPN', 'OBAT'],
            ['300.01.B06', 'BERLIAN ORTHOTIC', 'NON PPN', 'ALKES'],
            ['300.01.B07', 'PT BINTANG SAUDARA SEMESTA JAYA', 'PPN', 'DENTAL'],
            ['300.01.B08', 'PT BINA ARTHA SEMESTA', 'PPN', 'ALKES'],
            ['300.01.B09', 'BINTANG ROPANJOS PRIMA', 'NON PPN', 'ALKES'],
            ['300.01.B10', 'CV BINTANG CHARISA', 'PPN', 'CHEMICAL LAUNDRY'],
            ['300.01.B11', 'PT BERKATINDO NUSANTARA BERSINAR', 'PPN', 'CHEMICAL IPAL'],
            ['300.01.B12', 'CV BINTANG MULIA ABADI', 'PPN', 'GENSET'],
            ['300.01.B13', 'PT BUNDA GLOBAL PHARMA', 'PPN', 'OBAT'],
            ['300.01.B14', 'PT BISAWI TUMBUH SELARAS', 'PPN', 'ALKES'],
            ['300.01.B15', 'PT BIRU INDOKON INDONESIA', 'PPN', 'GYPSUM'],
            ['300.01.B16', 'BINTANG TIMUR JAYA', 'NON PPN', 'MESIN'],
            ['300.01.B17', 'CV BIMA SAKTI ENVIRO', 'PPN', 'CHEMICAL SANITASI'],
            ['300.01.B18', 'BERAS SEHATI', 'NON PPN', 'BERAS'],
            ['300.01.B19', 'BINTANG MAS', 'NON PPN', 'GIZI MINYAK, KECAP,PENYEDAP'],
            ['300.01.B20', 'PT BERKAT PERMATA RAJAWALI', 'PPN', 'ALKES'],
            ['300.01.C01', 'CV CAZA MANDIRI', 'NON PPN', 'ALKES'],
            ['300.01.C02', 'PT CITRA MANDIRI PROTEKSI', 'PPN', 'APAR'],
            ['300.01.C03', 'PT CITRA DIAN PRATAMA', 'PPN', 'ALKES'],
            ['300.01.C04', 'PT COBRA DENTAL INDONESIA', 'PPN', 'ALKES'],
            ['300.01.C05', 'CV USAHA BERSAMA', 'NON PPN', 'ALKES'],
            ['300.01.C06', 'PT CIOMAS ADISATWA (JAPFA)', 'PPN', 'AYAM'],
            ['300.01.C07', 'PT CAHAYA DUA DELAPAN', 'PPN', 'ALAT ENDOSCOPY'],
            ['300.01.C08', 'PT CITRA MEDICA ALKESTRON', 'PPN', 'ALKES'],
            ['300.01.D01', 'PT DIMAS ANDALAS MAKMUR', 'PPN', 'OBAT'],
            ['300.01.D02', 'PT DAYA MUDA AGUNG', 'PPN', 'OBAT'],
            ['300.01.D03', 'PT DISTRIVERSA BUANAMAS INHEALTH', 'PPN', 'OBAT'],
            ['300.01.D04', 'PT DISTRIVERSA BUANAMAS', 'PPN', 'OBAT'],
            ['300.01.D05', 'PT DOS NI ROHA', 'PPN', 'OBAT'],
            ['300.01.D06', 'PT DAYA MUDA AGUNG LKPP', 'PPN', 'OBAT'],
            ['300.01.D07', 'PT DANVI MEDILAB PERKASA', 'PPN', 'MESIN LAUNDRY/ALKES'],
            ['300.01.D08', 'PT DUTA AFIAT', 'PPN', 'ALKES'],
            ['300.01.D09', 'DUNIA ANUGRAH ABADI', 'NON PPN', 'IMPORTIR'],
            ['300.01.D10', 'PT DIMAS ANDALAS MEDIKA', 'PPN', 'ALKES'],
            ['300.01.D11', 'CV DINAMIKA NUSANTARA KENCANA', 'PPN', 'AC GREE'],
            ['300.01.D12', 'PT DISTRINDO BINTANG AGUNG', 'PPN', 'OBAT'],
            ['300.01.D13', 'PT DODORINDO JAYA ABADI', 'PPN', 'ALKES'],
            ['300.01.D14', 'PT DUA FARMA MAHAKARSA', 'PPN', 'OBAT'],
            ['300.01.D15', 'PT DEKA INTEGRA MEDITAMA', 'PPN', 'MEDICAL SUPPLY'],
            ['300.01.E01', 'PT ENSEVAL PUTERA MEGATRADING TBK', 'PPN', 'OBAT'],
            ['300.01.E02', 'ERA GORDYN', 'NON PPN', 'LAKEN'],
            ['300.01.E03', 'PT ENDO MEDICA NUSANTARA', 'PPN', 'ALKES'],
            ['300.01.E04', 'PT ENSEVAL PUTERA MEGATRADING TBK INHEALTH', 'PPN', 'OBAT'],
            ['300.01.E05', 'PT EKAPERKASA REKABUANA', 'PPN', 'LIFT HYUNDAI'],
            ['300.01.E06', 'TOKO ERA ELECTRIC', 'NON PPN', 'ELEKTRIK/LISTRIK'],
            ['300.01.E07', 'CV ERA LESTARI', 'PPN', 'LISTRIK'],
            ['300.01.E08', 'PT EXPRAVET NASUBA', 'PPN', 'AYAM'],
            ['300.01.E09', 'PT ENSEVAL MEDIKA PRIMA', 'PPN', 'IT PENGGANTI INTIWID'],
            ['300.01.E10', 'PT ENSEVAL PUTERA MEGATRADING TBK LKPP', 'PPN', 'OBAT'],
            ['300.01.E11', 'PT ERA REJEKI ABADI', 'PPN', 'ALKES'],
            ['300.01.E12', 'PT ELO KARSA UTAMA', 'PPN', 'ALKES'],
            ['300.01.F01', 'PT IDS MEDICAL SYSTEMS INDONESIA', 'PPN', 'ALKES'],
            ['300.01.F02', 'PT JOVI KARUNIA JAYA', 'PPN', 'ALKES'],
            ['300.01.G01', 'PT GLOBAL MITRA PRIMA', 'PPN', 'OBAT'],
            ['300.01.G02', 'PT GLOBAL DENT', 'PPN', 'ALKES'],
            ['300.01.G03', 'CV GABE SUKSES MANDIRI (MARBUN)', 'NON PPN', 'GAS MEDIS'],
            ['300.01.G04', 'PT JAYA ABADI SIAGA', 'PPN', 'MINYAK SOLAR INDUSTRI'],
            ['300.01.G05', 'PT KHARISMA MITRA SEHATI', 'PPN', 'ALKES'],
            ['300.01.G06', 'PT GLOMED ADINATA PRIMA', 'PPN', 'POUCHES STERIL'],
            ['300.01.G07', 'PT GOBER MANDIRI INDONESIA', 'PPN', 'PIPA PUMBLING'],
            ['300.01.G08', 'CV GIAT MAS', 'NON PPN', 'ALKES'],
            ['300.01.G09', 'PT OPAL PERKASA SEJAHTERA', 'PPN', 'ALKES'],
            ['300.01.G10', 'PT GRHA SINAR ARYA', 'PPN', 'ACP/ALUCUBON'],
            ['300.01.G11', 'PT GE OPERATIONS INDONESIA', 'PPN', 'ALKES'],
            ['300.01.G12', 'PT GUMAPU BERKAT ABADI', 'PPN', 'BARANG ACP'],
            ['300.01.G13', 'PT GLOBAL DISPOMEDIKA', 'PPN', 'ALKES'],
            ['300.01.H01', 'PT ORTHOCARE INDONESIA', 'PPN', 'ALKES'],
            ['300.01.H02', 'PT PANCA PERSADA MEDIKA', 'PPN', 'ALKES'],
            ['300.01.H03', 'PT HEXALAB SUMATERA', 'PPN', 'ALKES'],
            ['300.01.I01', 'PT INDOFARMA GLOBAL MEDIKA', 'PPN', 'OBAT'],
            ['300.01.I02', 'PT ORTHOLIGHT INDOPRIMA MEDIKA', 'NON PPN', 'ALKES'],
            ['300.01.I03', 'PT INDOFARMA GLOBAL MEDIKA LKPP', 'PPN', 'OBAT'],
            ['300.01.I04', 'PT INTERGRASTA ARTHA NUSANTARA', 'PPN', 'ALKES'],
            ['300.01.I05', 'TOKO INTAN PLASTIK', 'NON PPN', 'PLASTIK'],
            ['300.01.I06', 'PT INDEC DIAGNOSTICS', 'PPN', 'ALKES'],
            ['300.01.I07', 'PT PETAN DAYA MEDICA', 'PPN', 'ALKES ENDOCSOPY DR.SABRI'],
            ['300.01.I08', 'PT ITAMA RANORAYA TBK', 'PPN', 'ALKES'],
            ['300.01.J01', 'PT PHARMA HEALTH CARE', 'PPN', 'ALKES'],
            ['300.01.J02', 'JOHAN KELAPA', 'NON PPN', 'KELAPA SANTAN'],
            ['300.01.J03', 'JAYA UTAMA BESI', 'NON PPN', 'BESI'],
            ['300.01.K01', 'PT KEBAYORAN PHARMA', 'PPN', 'OBAT'],
            ['300.01.K02', 'PT KIMIA FARMA TRADING & DISTRIBUTION', 'PPN', 'OBAT'],
            ['300.01.K03', 'PT KALLISTA PRIMA', 'PPN', 'OBAT'],
            ['300.01.K04', 'KARYA INDAH JAYA', 'NON PPN', 'PERCETAKAN'],
            ['300.01.K05', 'PT KEBAYORAN PHARMA INHEALTH', 'PPN', 'OBAT'],
            ['300.01.K06', 'CV KENCANA INDOLABEL', 'PPN', 'LABEL BARCODE'],
            ['300.01.K07', 'PT KAHAR DUTA SARANA', 'PPN', 'LABEL BARCODE'],
            ['300.01.K08', 'KITO GALLERY', 'NON PPN', 'KERAMIK'],
            ['300.01.K09', 'PT KAWI AGUNG KENCANA/OPPLE', 'PPN', 'LAMPU'],
            ['300.01.K10', 'PT KARYA GUNA ARGAMA', 'PPN', 'ALKES'],
            ['300.01.K11', 'PT KURNIA AGROTAMA SEJAHTERA', 'PPN', 'AYAM'],
            ['300.01.K12', 'PT KIMIA FARMA INHEALTH', 'PPN', 'OBAT'],
            ['300.01.K13', 'PT KIMIA FARMA LKPP', 'PPN', 'OBAT'],
            ['300.01.K14', 'PT KENCANA INTI MEDIKA', 'PPN', 'OBAT'],
            ['300.01.L01', 'LAIN-LAIN OBAT / RSU BUNDA THAMRIN', '#N/A', '#N/A'],
            ['300.01.L02', 'LAIN LAIN PERBEKALAN', 'NON PPN', 'LAIN LAIN PERBEKALAN'],
            ['300.01.L03', 'LAIN-LAIN GIZI', 'NON PPN', 'LAIN LAIN GIZI'],
            ['300.01.L04', 'LAIN-LAIN ALAT DOKTER', 'NON PPN', 'ALKES'],
            ['300.01.L05', 'LAIN-LAIN DP', 'PPN', 'PERBEKALAN'],
            ['300.01.L06', 'LOGAM PANGLONG', 'NON PPN', 'BANGUNAN'],
            ['300.01.L07', 'PT LINTEX PERSADA INDONESIA', 'PPN', 'LINEN'],
            ['300.01.L08', 'LAIN-LAIN ACEH', 'PPN', 'PERBEKALAN'],
            ['300.01.L09', 'LAIN-LAIN (TOKO)', 'NON PPN', 'MEDICAL SUPPLY'],
            ['300.01.L10', 'PT LUCKY MEDICAL INDONESIA', 'PPN', 'ALKES'],
            ['300.01.M01', 'PT MERAPI UTAMA PHARMA', 'PPN', 'OBAT'],
            ['300.01.M02', 'PT MENSA BINASUKSES', 'PPN', 'OBAT'],
            ['300.01.M03', 'PT MILLENNIUM PHARMACON INTERNATIONAL TBK', 'PPN', 'OBAT'],
            ['300.01.M04', 'PT MULTI PLUS MEDILAB', 'PPN', 'OBAT'],
            ['300.01.M05', 'PT MENSA BINASUKSES INHEALTH', 'PPN', 'OBAT'],
            ['300.01.M06', 'PT MERAPI UTAMA PHARMA INHEALTH', 'PPN', 'OBAT'],
            ['300.01.M07', 'PT METRUM ALKESTRON', 'NON PPN', 'ALKES'],
            ['300.01.M08', 'PT MERAPI UTAMA PHARMA LKPP', 'PPN', 'OBAT'],
            ['300.01.M09', 'PT SUKANDA DJAYA', 'PPN', 'BAHAN GIZI'],
            ['300.01.M10', 'PT MILLENNIUM PHARMACON INTERNATIONAL TBK LKPP', 'PPN', 'OBAT'],
            ['300.01.M11', 'PT MEKADA ABADI', 'PPN', 'OBAT'],
            ['300.01.M12', 'PT SIEMENS HEALTHINEERS INDONESIA', 'PPN', 'MESIN ESWL'],
            ['300.01.M13', 'MIKI KACA', 'NON PPN', 'KACA'],
            ['300.01.M14', 'PT MAHANA PHARMA ABADI', 'PPN', 'OBAT'],
            ['300.01.M15', 'PT MARGA NUSANTARA JAYA', 'PPN', 'OBAT'],
            ['300.01.M16', 'TOKO MAJU/AKIAN', 'NON PPN', 'BAHAN GIZI'],
            ['300.01.M17', 'PT PRIMA ALKESINDO NUSANTARA', 'PPN', 'ALKES'],
            ['300.01.M18', 'PT MEGA INTI MAKMUR MEDIKA', 'PPN', 'ALKES'],
            ['300.01.M19', 'MAXIDATA', 'NON PPN', 'REFILL TONER'],
            ['300.01.M20', 'MAJU JAYA', 'NON PPN', 'PLASTIK'],
            ['300.01.M21', 'PT MESTIKA MAKMUR PERSADA JAYA', 'PPN', 'BANTEX'],
            ['300.01.M22', 'MODERN ELEKTRONIK', 'NON PPN', 'SERVICE TV'],
            ['300.01.M23', 'PT MITRA FAJAR SELARAS', 'PPN', 'ALKES'],
            ['300.01.M24', 'PT MITRA KHARISMA PERKASA', 'PPN', 'CHEMICAL AIR BERSIH'],
            ['300.01.M25', 'MULTI CORE', 'NON PPN', 'CCTV'],
            ['300.01.M26', 'MANDIRI JAYA TEKNIK', 'NON PPN', 'ALAT TEKNIK'],
            ['300.01.M27', 'CV MULTI JAYA TEKNIK', 'PPN', 'BARANG TEKNIK'],
            ['300.01.M28', 'TOKO MULIA', 'NON PPN', 'PUMBLING/BANGUNAN'],
            ['300.01.M29', 'PT CAMAR USAHA TATA', 'PPN', 'OBAT'],
            ['300.01.M30', 'PT MULYA HUSADA JAYA', 'PPN', 'ALKES'],
            ['300.01.M31', 'MEDIATAMA', 'NON PPN', 'KOMPUTER'],
            ['300.01.M32', 'PT MAHMI JAYA ABADI', 'PPN', 'ALKES'],
            ['300.01.M33', 'PT MARKS MEDAN JAYA', 'PPN', 'BAHAN ACP'],
            ['300.01.M34', 'PT MEGA INTER DISTRINDO', 'PPN', 'OBAT'],
            ['300.01.M35', 'PT MEDI KHARISMA INTERNATIONAL', 'PPN', 'ALKES'],
            ['300.01.M36', 'PT MARTHA INTI PERSADA', 'PPN', 'ALKES'],
            ['300.01.N01', 'NAGA JAYA', 'NON PPN', 'PUMBLING/BANGUNAN'],
            ['300.01.N02', 'PT NUSA ASIA MEDIKA', 'PPN', 'ALKES'],
            ['300.01.N03', 'PT NUGRA KARSERA', 'PPN', 'ALKES'],
            ['300.01.N04', 'NEW JET COOL', 'NON PPN', 'AC'],
            ['300.01.N05', 'HOGI', 'NON PPN', 'ALKES'],
            ['300.01.N06', 'PT DENTSPLY', 'PPN', 'ALKES'],
            ['300.01.O01', 'OK COM', 'NON PPN', 'KOMPUTER'],
            ['300.01.P01', 'PT PARIT PADANG GLOBAL', 'PPN', 'OBAT'],
            ['300.01.P02', 'PT PARIT PADANG GLOBAL INHEALTH', 'PPN', 'OBAT'],
            ['300.01.P03', 'PT PARIT PADANG GLOBAL LKPP', 'PPN', 'OBAT'],
            ['300.01.P04', 'PT PENTA VALENT TBK', 'PPN', 'OBAT'],
            ['300.01.P05', 'PT PACIFIC DENTAL INDONESIA', 'PPN', 'ALKES'],
            ['300.01.P06', 'LAIN PERBEKALAN', 'PPN', 'PERBEKALAN'],
            ['300.01.P07', 'PONDOK BERAS', 'NON PPN', 'BERAS'],
            ['300.01.P08', 'PANCA SETIA BAN', 'NON PPN', 'BAN'],
            ['300.01.P09', 'PT PUTRA OTTO MANDIRI', 'PPN', 'GENSET'],
            ['300.01.P10', 'PT PRIMA HEALTH CARE', 'PPN', 'ALKES'],
            ['300.01.P11', 'PT PELITA BIOMEDICAL', 'PPN', 'ALKES'],
            ['300.01.P12', 'PERKEBUNAN NUSANTARA IV REGIONAL II', 'PPN', 'BUBUK TEHH'],
            ['300.01.P13', 'PT PRASASTI NUSANTARA SUKSES', 'PPN', 'ALKES'],
            ['300.01.R01', 'PT RAJAWALI NUSINDO', 'PPN', 'OBAT'],
            ['300.01.R02', 'PT RAJAWALI NUSINDO LKPP', 'PPN', 'OBAT'],
            ['300.01.R03', 'PT FORTUNA HEALTHCARE', 'PPN', 'ALKES'],
            ['300.01.R04', 'REFIL CENTER', 'NON PPN', 'RIBBON PRINTER'],
            ['300.01.R05', 'RONI - TELUR', 'NON PPN', 'TELUR'],
            ['300.01.R06', 'PT REKA MILLENIUM SELARAS', 'PPN', 'ALKES'],
            ['300.01.R07', 'PT REVASS UTAMA MEDIKA', 'PPN', 'ALKES'],
            ['300.01.R08', 'TOKO RAJAWALI (PECAH BELAH)', 'NON PPN', 'PECAH BELAH'],
            ['300.01.R09', 'CV ORGANO KIMIA', 'NON PPN', 'OBAT'],
            ['300.01.R10', 'PT RAYTY BROTHERS', 'PPN', 'BED PASIEN'],
            ['300.01.R11', 'PT ROYAL IMPLANTAMA MANDIRI', 'PPN', 'ALKES'],
            ['300.01.S01', 'CV SURYA NUSANTARA SAFETY', 'PPN', 'SEPATU SAFETY'],
            ['300.01.S02', 'PT SUMBER GIAT UTAMA FARMA', 'PPN', 'OBAT'],
            ['300.01.S03', 'PT SAPTA MANDIRI INDONESIA', 'PPN', 'ALKES'],
            ['300.01.S04', 'SHOPEE/TOKOPEDIA', 'NON PPN', 'ALKES'],
            ['300.01.S05', 'PT SAPTA SARI TAMA', 'PPN', 'OBAT'],
            ['300.01.S06', 'PT SENTERAL INTI GAS', 'PPN', 'GAS MEDIS'],
            ['300.01.S07', 'PT SINGA ASIA PERKASA UTAMA', 'PPN', 'ALKES'],
            ['300.01.S08', 'PT SOLOCONE INDUSTRY (SCI)', 'PPN', 'KERTAS OBAT'],
            ['300.01.S09', 'TOKO SINAR', 'NON PPN', 'ELEKTRIK/LISTRIK'],
            ['300.01.S10', 'PT SUMBER REZEKI BERSAMA', 'PPN', 'ALKES'],
            ['300.01.S11', 'PT SUMBER UTAMA MEDICALINDO', 'PPN', 'ALKES'],
            ['300.01.S12', 'PT SINAR REZEKIMAS MAKMUR', 'PPN', 'AC'],
            ['300.01.S13', 'PT SUKSES JAYA ALKESINDO', 'PPN', 'ALKES'],
            ['300.01.S14', 'PT SUGIARTO DENTAL SEJAHTERA', 'PPN', 'ALKES'],
            ['300.01.S15', 'PT SUPRAMEDIKA', 'PPN', 'OBAT'],
            ['300.01.S16', 'PT SURYA MEDICANDA LESTARI', 'PPN', 'HYDROGEN PEROXYD'],
            ['300.01.S17', 'PT SINAR BARU MEDAN', 'PPN', 'KABEL'],
            ['300.01.S18', 'CV SAUDARA TEKNIK ENGINEERING', 'PPN', 'MESIN POMPA'],
            ['300.01.S19', 'PT SELTECH UTAMA MANDIRI', 'PPN', 'LIFT FOXLIFT'],
            ['300.01.S20', 'SUMBER BARU BATERAI', 'NON PPN', 'BATERAI'],
            ['300.01.S21', 'PT SURGIKA ALKESINDO', 'PPN', 'ALKES'],
            ['300.01.S22', 'PT SONNA MEDIKA JAYA', 'PPN', 'ALKES'],
            ['300.01.S23', 'PT SUKSES MENTARI TIMUR', 'PPN', 'LAMPU'],
            ['300.01.S24', 'PT SKBIO NUSA MEDICA', 'PPN', 'ALKES'],
            ['300.01.S25', 'S&J SOLUSINDO', 'NON PPN', 'EXT TELEPON'],
            ['300.01.S26', 'SEHAT JAYA', 'NON PPN', 'ALKES dan OBAT (BAHAN GIGI)'],
            ['300.01.S27', 'PT SAPTA SARI TAMA LKPP', 'PPN', 'OBAT'],
            ['300.01.T01', 'PT TEMPO', 'PPN', 'OBAT'],
            ['300.01.T02', 'PT TEMPO INHEALTH', 'PPN', 'OBAT'],
            ['300.01.T03', 'PT TIRTA KIMIA ENGINEERING', 'PPN', 'PAC DAN CHLORINE'],
            ['300.01.T04', 'PT TAWADA HEALTHCARE', 'PPN', 'ALKES'],
            ['300.01.T05', 'PT TRANSMEDIC INDONESIA', 'PPN', 'ALKES'],
            ['300.01.T06', 'PT TRI SAPTA JAYA', 'PPN', 'OBAT'],
            ['300.01.T07', 'PT TIRTA MEDICAL INDONESIA', 'PPN', 'ALKES'],
            ['300.01.T08', 'PT TRICOM SAKTI', 'PPN', 'KOMPUTER'],
            ['300.01.T09', 'PT THOMASONG NIRWANA', 'PPN', 'ALKES'],
            ['300.01.T10', 'TRIJAYA', 'NON PPN', 'KOMPUTER'],
            ['300.01.T11', 'PT EDISON DUTA SARANA', 'PPN', 'ALKES'],
            ['300.01.T12', 'CV TRIBANGUN MAKMUR', 'PPN', 'UPS'],
            ['300.01.T13', 'PT TIRTA SUMBER MENARA LESTARI (AQUA)', 'NON PPN', 'AQUA GALON'],
            ['300.01.T14', 'PT TRITUNGGAL KENCANA NUSANTARA', 'PPN', 'HANDWASH'],
            ['300.01.T15', 'PT TIRTASARI SUMBER MURNI', 'PPN', 'INDODES'],
            ['300.01.T16', 'TOTAL KARYA BERKAH', 'PPN', 'ALKRILIK CUSTOM'],
            ['300.01.T17', 'PT TRISA LIKUID FARMA', 'PPN', 'ALKES'],
            ['300.01.T18', 'TOKO TERMINAL ALKES MEDAN', 'NON PPN', 'ALKES'],
            ['300.01.U01', 'PT UNITED DICO CITAS', 'PPN', 'OBAT'],
            ['300.01.U02', 'TOKO UTARA', 'NON PPN', 'TISSUE'],
            ['300.01.U03', 'UBIN MAS', 'NON PPN', 'SANITARI'],
            ['300.01.U04', 'PT KANAYA MAKMUR ABADI', 'PPN', 'ALKES'],
            ['300.01.U05', 'PT ULTRAADILESTARI STELLAPERKASA', 'PPN', 'DELMONTE'],
            ['300.01.V01', 'VIRGO', 'NON PPN', 'PERCETAKAN'],
            ['300.01.W01', 'PT WEGO MEDIKA INDONESIA', 'PPN', 'ALKES'],
            ['300.01.W02', 'PT WAHANA MAKMUR ENGINEERING', 'PPN', 'POMPA'],
            ['300.01.W03', 'PT WORCKHARDT PHARMA INDO', 'PPN', 'ALKES'],
            ['300.01.Y01', 'PT WIXA MEDISA JAYA', 'PPN', 'ALKES'],
        ];

        foreach ($suppliers as $s) {
            DB::table('suppliers')->insert([
                'gl_code'     => $s[0],
                'name'        => $s[1],
                'address'     => '-',
                'is_ppn'      => strtoupper($s[2]) === 'PPN',
                'notes'  => $s[3],
                'editor_id'   => 1,
                'created_at'  => now(),
                'updated_at'  => now(),
            ]);
        }
    }
}
